### ISSUE TITLE
Installation fails with ChildIOException

### ISSUE THREAD

**Issue by alexprp** [arumugamlab/MIntO#16]
Hi there, I'm getting a snakemake error that I'm not sure how to resolve when installing MIntO.

My install command: 

```
snakemake\
	--use-conda\
	--restart-times 1\
	--keep-going\
	--latency-wait 60\
	--jobs 2\
	--conda-prefix $MINTO_DIR/conda_env\
	--shadow-prefix /work/<usrname>/minto\
	--snakefile $MINTO_DIR/smk/dependencies.smk\
	--configfile $MINTO_DIR/configuration/dependencies.yaml
```
(I've changed server-specific details for privacy)

I get the following output:

```
*******************************
 Reading configuration yaml file: 
 *******************************
  
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
$MINTO_DIR/data/kofam_db/profiles
$MINTO_DIR/data/kofam_db/profiles/prokaryote.hal

```
I have never written snakemake scripts, but Googling around the `ChildIOException` error suggested that 
changing one of the nested things here from `output` to `params` can help, so when I play around with that in  `dependencies.smk` it leads to the following error instead:

```
 *******************************
 Reading configuration yaml file: 
 *******************************
  
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
$MINTO_DIR/data/rRNA_databases/idx
$MINTO_DIR/data/rRNA_databases/idx/rRNA_db_index.log
```

Changing either one to a `param` breaks the script in other ways. My snakemake version is 5.10.0

I am following instructions on the wiki and am not sure what to do now; any guidance?

**Comment by microbiomix** [comment]
Hi, Sorry for the delayed response.

`Snakemake` interfaces in `5.10.0` were quite different, so MIntO is not compatible with those older versions. I could also reproduce the same error using `5.10.0`. MIntO expects `Snakemake` to be version `7.x.x`. The latest version `7.32.4` works fine.

We have now updated the installation instructions on how to specifically install `Snakemake` version `7` and also python `v3.11` to ensure compatibility with MIntO. Please wipe your current installation and start fresh, and get MIntO stable release `2.0.0`. If you run into any trouble, please do let us know.

**Comment by alexprp** [comment]
Thank you very much; it turns out my HPC server had an odd behavior of defaulting to the `Snakemake` installation in a different environment, so this was not an issues with your software. Regardless, this helped me figure out the issue and I am grateful! Marking resolved.
