### ISSUE TITLE
6-taxa_profile: metaphlan discordance between relative_abundance and estimated_number_of_reads

### ISSUE THREAD

**Issue by NicoleTreichel** [arumugamlab/MIntO#21]
Dear MIntO Team,

First of all, thank you for providing this nice workflow. 
I realized a discrepancy between relative_abundance and estimated_number_of_reads in the output of metaphlan. For some clades the estimated_number_of_reads was 0, even if the relative abundance was positive.
A search of the methaphlan forum suggested an update of the database. After updating mpa_vOct22_CHOCOPhlAnSGB_202212 to mpa_vJun23_CHOCOPhlAnSGB_202307 it now works fine for me.
So my suggestion would be to update the default DB in the MIntO workflow to the Jun23 version.

Best regards,
Nicole

**Comment by jszarvas** [comment]
Thanks for raising the issue and the tip! The metaphlan database change was done in 767433cd38b2aa0ed580c87a989d438247634ac0
