### ISSUE TITLE
MissingInputException in rule gene_annot_merge in file /MIntO/smk/gene_annotation.smk, line 183:

### ISSUE THREAD

**Issue by anzhi525** [arumugamlab/MIntO#5]
*******************************
 Reading configuration yaml file
 *******************************

WARNING in  configuration yaml file : MIntO is using "/ssd1/MIntO/MIntO/mypath/IBD_tutorial/metaG/8-1-binning/mags_generation_pipeline/prokka" as PATH_reference variable
Building DAG of jobs...
MissingInputException in rule gene_annot_merge in file /ssd1/MIntO/MIntO/smk/gene_annotation.smk, line 183:
Missing input files for rule gene_annot_merge:
    output: /ssd1/MIntO/MIntO/mypath/IBD_tutorial/DB/9-MAGs-prokka-post-analysis/CD_transl/MAGs_genes_translated_cds.faa, /ssd1/MIntO/MIntO/mypath/IBD_tutorial/DB/9-MAGs-prokka-post-analysis/genomes_list.txt, /ssd1/MIntO/MIntO/mypath/IBD_tutorial/DB/9-MAGs-prokka-post-analysis/GFF/MAGs_genes.bed, /ssd1/MIntO/MIntO/mypath/IBD_tutorial/DB/9-MAGs-prokka-post-analysis/GFF/MAGs_genes.header-modif.coord_correct.bed
    wildcards: wd=/ssd1/MIntO/MIntO/mypath/IBD_tutorial
    affected files:
        /ssd1/MIntO/MIntO/mypath/IBD_tutorial/metaG/8-1-binning/mags_generation_pipeline/prokka

**Comment by anzhi525** [comment]
i don't know how to solve the problem，please help me，thanks

**Comment by microbiomix** [comment]
Hello,

What are the contents of the directory `/ssd1/MIntO/MIntO/mypath/IBD_tutorial/metaG/8-1-binning/mags_generation_pipeline/prokka`? 

This is the input to this rule, and `Snakemake` is complaining that it does not exist. After generating MAGs with `RUN_PROKKA: yes` in config file, you should have 5 folders corresponding to 5 MAGs. Do you see that?

**Comment by arumugamlab** [comment]
Closing as there was no feedback or follow up. Please reopen if it continues to be an issue.
