### ISSUE TITLE
Make host-removal and other QC steps optional

### ISSUE THREAD

**Issue by CJREID** [arumugamlab/MIntO#59]
Hi there,

I was wondering if it would be possible to make certain rules within the QC process optional or make QC optional all together.

At present it is unavoidable for downstream steps even though I already have assembled MAGs and both metaG and metaT reads that I have QC'd myself. Furthermore, I'm working on soil metagenomes/metatranscriptomes with many samples so the host removal step is a time-consuming redundancy for my dataset. 

Thanks,
Cam

**Comment by microbiomix** [comment]
Hi Cam,

We have made some recent changes to accommodate starting the pipeline at later stages. Now you can start at `assembly.smk` step; or even use your own MAGs and high-quality reads to start at `gene_annotation.smk` step. You can find some help on how to do this at our [FAQ](https://github.com/arumugamlab/MIntO/wiki/Frequently-Asked-Questions) page. Please use the latest version from the repository.

For now, we have not implemented skipping intermediate steps. E.g., you cannot ask for quality-trimming to be done but any later steps (length-trimming or host-filtering) to be skipped. Perhaps we will enable this flexibility one day.

Hope this helps. Please let us know if this works and we are happy to help if you run into trouble.

Best,
Mani

**Comment by CJREID** [comment]
Hi Mani,

Many thanks for the update!

I ended up just running QC anyway and feeding a fasta full of Ns to 'skip' the host filtering. I have also successfully run `gene_annotation.smk` on my MAGs. I am now in the process of running `gene_abundance.smk` for both metaG and metaT.

It's good to know that I can start from annotation in the future if I have a similar dataset :)

Cheers,

Cam

**Comment by microbiomix** [comment]
Hi Cam,

I will close this issue for now. Please reopen if you run into issues in the future.

Best,
Mani
